name: Deploy
on:
  push:
    branches:
      - dev
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy-api:
      name: Deploy API
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: cd api && flyctl deploy --remote-only
  deploy-client:
      name: Deploy Client App
      runs-on: ubuntu-latest
      env:
        VITE_API_ENDPOINT: "https://nameless-terror-api.fly.dev/"
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18.x
            cache: 'npm'

        - name: Install dependencies
          run: cd client && npm ci --production

        - name: Build
          run: cd client && npm run build

        - name: Deploy
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: cd api && flyctl deploy --remote-only